# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
# Force build: 1
version: 2.1

jobs:
  sd-build:
    docker:
      - image: cimg/python:3.12
    resource_class: small
    working_directory: ~/h2scm-supply-demand/backend
    steps:
      - checkout:
          path: ~/h2scm-supply-demand
      - run:
          name: install rsync
          command: sudo add-apt-repository main -y && sudo apt-get install rsync
      - run:
          name: bundle lambdas
          command: cd lambdas/bundle && ./bundle.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - "h2scm-supply-demand/backend"
  sd-deploy:
    docker:
      - image: cimg/deploy:2023.06.1
    resource_class: small
    working_directory: ~/h2scm-supply-demand/backend/infra
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: init
          command: terraform init
      - run:
          name: plan
          command: terraform plan -var-file prod.tfvars --out prod.plan
      - run:
          name: apply
          command: terraform apply prod.plan

workflows:
  deploy-sd:
    jobs:
      - sd-build:
          context: scm-sd-infra-prod
          filters:
            branches:
              only: main
      - sd-deploy:
          context: scm-sd-infra-prod
          requires: [sd-build]
